In [ ]:
"""
condition
capitalization 前 300
近 3 個月 volume >= threshold
factor:
成長：35%
    營收 YoY, EPS YoY, 近一季營收 std
財務：30%
    一年 ROE avg
創新：20%
    capex 資本支出/營收
技術：
    30 ma > 120 ma
"""

In [2]:
import yfinance as yf

In [3]:
from 國宏.factorize import fetch_factors, fetch_factors_batch

# 單檔
result = fetch_factors("AAPL")

# 批次
df = fetch_factors_batch(["AAPL", "MSFT", "GOOGL"])
df

        revenue_yoy   eps_yoy   revenue_std   roe_avg  capex_ratio  ma_bullish
ticker
AAPL       0.156525  0.183333  2.352753e+10  0.394202     0.016507       False
MSFT       0.167179  0.597523  4.671991e+09  0.083581     0.367601       False
GOOGL      0.179954  0.311628  1.004767e+10  0.087780     0.244674        True

In [4]:
tAAPL = yf.Ticker('AAPL')
inc = tAAPL.quarterly_income_stmt
bs = tAAPL.quarterly_balance_sheet
cf = tAAPL.quarterly_cashflow

In [6]:
bs

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
Ordinary Shares Number,1.469793e+10,1.477326e+10,1.485672e+10,1.493932e+10,1.503787e+10,NaN
Share Issued,1.469793e+10,1.477326e+10,1.485672e+10,1.493932e+10,1.503787e+10,NaN
Net Debt,4.519200e+10,6.272300e+10,6.542900e+10,7.002400e+10,6.650000e+10,NaN
Total Debt,9.050900e+10,9.865700e+10,1.016980e+11,9.818600e+10,9.679900e+10,NaN
Tangible Book Value,8.819000e+10,7.373300e+10,6.583000e+10,6.679600e+10,6.675800e+10,NaN
...,...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,6.690700e+10,5.469700e+10,5.537200e+10,4.849800e+10,5.377500e+10,NaN
Other Short Term Investments,2.159000e+10,1.876300e+10,1.910300e+10,2.033600e+10,2.347600e+10,NaN
Cash And Cash Equivalents,4.531700e+10,3.593400e+10,3.626900e+10,2.816200e+10,3.029900e+10,NaN
Cash Equivalents,1.449100e+10,7.667000e+09,9.583000e+09,3.101000e+09,3.226000e+09,NaN
Cash Financial,3.082600e+10,2.826700e+10,2.668600e+10,2.506100e+10,2.707300e+10,NaN