In [ ]:
import pandas as pd
import numpy as np

from scipy.stats import hypergeom

In [42]:
# 平常
# multiplier = {
#     1: {1: 2},
#     2: {2: 3, 1: 1},
#     3: {3: 20, 2: 2},
#     4: {4: 40, 3: 4, 2: 1},
#     5: {5: 300, 4: 20, 3: 2},
#     6: {6: 1000, 5: 40, 4: 8, 3: 1},
#     7: {7: 3200, 6: 120, 5: 12, 4: 2, 3: 1},
#     8: {8: 20000, 7: 800, 6: 40, 5: 8, 4: 1, 0: 1},
#     9: {9: 40000, 8: 4000, 7: 120, 6: 20, 5: 4, 4: 1, 0: 1},
#     10: {10: 200000, 9: 10000, 8: 1000, 7: 100, 6: 10, 5: 1, 0: 1}
# }

# 加碼
multiplier = {
    1: {1: 3},
    2: {2: 6, 1: 1},
    3: {3: 40, 2: 2},
    4: {4: 80, 3: 6, 2: 1},
    5: {5: 400, 4: 24, 3: 2},
    6: {6: 2000, 5: 48, 4: 8, 3: 1},
    7: {7: 3200, 6: 120, 5: 12, 4: 2, 3: 1},
    8: {8: 20000, 7: 800, 6: 40, 5: 8, 4: 1, 0: 1},
    9: {9: 40000, 8: 4000, 7: 120, 6: 20, 5: 4, 4: 1, 0: 1},
    10: {10: 200000, 9: 10000, 8: 1000, 7: 100, 6: 10, 5: 1, 0: 1}
}

In [ ]:
N, n = 80, 20
x_vals = np.arange(0, 11)
stars_list = sorted(multiplier.keys())

# 1) 機率矩陣 P
P = pd.DataFrame(0.0, index=x_vals, columns=stars_list)
for K in stars_list:
    P.loc[x_vals, K] = hypergeom.pmf(x_vals, N, K, n)

# 2) 倍數矩陣 M
M = pd.DataFrame(0.0, index=x_vals, columns=stars_list)
for s, pay in multiplier.items():
    for x, m in pay.items():
        M.loc[x, s] = m
M = M - 1 # 扣掉本金

# 3) 期望倍數（每列）
EV = (P * M).sum(axis=0)

pd.options.display.float_format = "{:.6f}".format
display(P)       # 機率表
display(M)       # 倍數表
display(EV)      # 期望倍數

,1,2,3,4,5,6,7,8,9,10
0,0.750000,0.560127,0.416504,0.308321,0.227184,0.166602,0.121574,0.088266,0.063748,0.045791
1,0.250000,0.379747,0.430867,0.432732,0.405686,0.363495,0.315193,0.266464,0.220666,0.179571
2,0.000000,0.060127,0.138754,0.212635,0.270457,0.308321,0.326654,0.328146,0.316426,0.295257
3,0.000000,0.000000,0.013875,0.043248,0.083935,0.129820,0.174993,0.214786,0.246109,0.267402
4,0.000000,0.000000,0.000000,0.003063,0.012092,0.028538,0.052191,0.081504,0.114105,0.147319
5,0.000000,0.000000,0.000000,0.000000,0.000645,0.003096,0.008639,0.018303,0.032601,0.051428
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000129,0.000732,0.002367,0.005720,0.011479
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000024,0.000160,0.000592,0.001611
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000004,0.000033,0.000135
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000001,0.000006
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

,1,2,3,4,5,6,7,8,9,10
0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000
1,2.000000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
2,-1.000000,5.000000,1.000000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
3,-1.000000,-1.000000,39.000000,5.000000,1.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000
4,-1.000000,-1.000000,-1.000000,79.000000,23.000000,7.000000,1.000000,0.000000,0.000000,-1.000000
5,-1.000000,-1.000000,-1.000000,-1.000000,399.000000,47.000000,11.000000,7.000000,3.000000,0.000000
6,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1999.000000,119.000000,39.000000,19.000000,9.000000
7,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3199.000000,799.000000,119.000000,99.000000
8,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,19999.000000,3999.000000,999.000000
9,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,39999.000000,9999.000000
10,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,199999.000000

1    -0.250000
2    -0.259494
3    -0.167478
4    -0.282806
5    -0.283944
6    -0.235317
7    -0.451025
8    -0.373863
9    -0.347008
10   -0.407805
dtype: float64